# Generated by Django 4.0.5 on 2022-07-02 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_qty',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
